apiVersion: v1
kind: Secret
metadata:
  name: convocatorias-secrets
type: Opaque
data:
  GOOGLE_CREDENTIALS_PATH: {{ .FilesGet "gcp-credentials.json" | b64enc }}
  SLACK_WEBHOOK_URL: {{ .Values.slackWebhook | b64enc }}
  TEAMS_WEBHOOK_URL: {{ .Values.teamsWebhook | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysqlPassword | b64enc }}